### Create a new report
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "toyota",
  "model": "camry",
  "year": 2015,
  "mileage": 100000,
  "lng": 0,
  "lat": 0,
  "price": 50000
}

### Approve an existing report
PATCH http://localhost:3000/reports/5
content-type: application/json

{
  "approved": true
}

### Get an estimate for an exsitng vehicle
GET http://localhost:3000/reports?make=toyota&model=camry&year=2015&mileage=100000&lng=0&lat=0